version: '3'
services:
  db:
    image: 'postgres:13'
    container_name: 'gql-presentation-pg'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
volumes:
  dive-admin:
